apiVersion: skaffold/v2beta27
kind: Config
metadata:
  name: kube-system
profiles:
  - name: local
    activation:
      - kubeContext: minikube
    deploy:
      helm:
        releases:
          - name: kube-system
            chartPath: charts/kube-system
            namespace: kube-system
            valuesFiles:
              - charts/jenkins/values.local.yaml
---

apiVersion: skaffold/v2beta27
kind: Config
metadata:
  name: jenkins
profiles:
  - name: local
    activation:
      - kubeContext: minikube
    build:
      tagPolicy:
        sha256: {}
      artifacts:
        - image: johnnyhuy/jenkins
          context: apps/jenkins
          docker: {}
        - image: johnnyhuy/jenkins-node
          context: apps/jenkins/agents/node
          docker: {}
        - image: johnnyhuy/jenkins-gradle
          context: apps/jenkins/agents/gradle
          docker: {}
    deploy:
      helm:
        releases:
          - name: jenkins
            chartPath: charts/jenkins
            namespace: jenkins
            createNamespace: true
            valuesFiles:
              - charts/jenkins/values.local.yaml
            setValueTemplates:
              jenkins.controller.image: "{{ .IMAGE_NAME }}"
              jenkins.controller.tag: "{{ .IMAGE_TAG }}"
            imageStrategy:
              helm: {}
